#!/usr/bin/env python3
"""
Mirror's Edge Catalyst - Community Server Patch Helper
======================================================
Researched and reverse engineered by Destiny Creates
Patches the Windows hosts file (or /etc/hosts on Linux) to redirect
all EA backend traffic to a community server.

Also shows what the game binary expects so mod developers can create
a binary patch to hardcode community server addresses.

Reverse engineered from MirrorsEdgeCatalyst.exe
"""

import os
import sys
import platform
import argparse
import re
import shutil
from datetime import datetime

# ---------------------------------------------------------------------------
# All EA hostnames that need redirecting (from binary string extraction)
# ---------------------------------------------------------------------------
EA_HOSTS = {
    # GOS Redirector - this is the FIRST contact point, most critical
    'winter15.gosredirector.ea.com':       'redirector',
    # Staging/dev redirectors (game has all 4 hardcoded)
    'winter15.gosredirector.scert.ea.com': 'redirector_scert',
    'winter15.gosredirector.sdev.ea.com':  'redirector_sdev',
    'winter15.gosredirector.stest.ea.com': 'redirector_stest',
    # Nucleus auth (OAuth token exchange)
    'peach.online.ea.com':                 'nucleus_auth',
    # QoS / ping site measurement
    'gosca.ea.com':                        'qos_server',
    # NAT traversal / demangler
    'demangler.ea.com':                    'nat_traversal',
}

# Optional: also block telemetry (game sends telemetry to these)
EA_TELEMETRY_HOSTS = [
    'data2.online.ea.com',
    'datad.online.ea.com',
    'eaassets-a.akamaihd.net',
]

HOSTS_MARKER_START = '# MEC-Community-Server-Start'
HOSTS_MARKER_END   = '# MEC-Community-Server-End'


def get_hosts_path() -> str:
    if platform.system() == 'Windows':
        return r'C:\Windows\System32\drivers\etc\hosts'
    return '/etc/hosts'


def read_hosts(path: str) -> str:
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        return f.read()


def remove_existing_patch(content: str) -> str:
    pattern = rf'{re.escape(HOSTS_MARKER_START)}.*?{re.escape(HOSTS_MARKER_END)}\n?'
    return re.sub(pattern, '', content, flags=re.DOTALL)


def build_patch_block(community_ip: str,
                      block_telemetry: bool = True) -> str:
    lines = [HOSTS_MARKER_START,
             f'# Generated by community_patch.py on {datetime.now().isoformat()}',
             f'# Community server: {community_ip}',
             '']
    for host, role in EA_HOSTS.items():
        lines.append(f'{community_ip:<20} {host}  # {role}')
    if block_telemetry:
        lines.append('')
        lines.append('# Blocked EA telemetry (optional)')
        for host in EA_TELEMETRY_HOSTS:
            lines.append(f'{"127.0.0.1":<20} {host}  # blocked')
    lines.append(HOSTS_MARKER_END)
    return '\n'.join(lines) + '\n'


def apply_patch(community_ip: str, block_telemetry: bool = True,
                dry_run: bool = False):
    path = get_hosts_path()
    print(f'[*] Hosts file: {path}')

    content = read_hosts(path)
    content = remove_existing_patch(content)
    patch   = build_patch_block(community_ip, block_telemetry)
    new_content = content.rstrip('\n') + '\n\n' + patch

    if dry_run:
        print('[DRY RUN] Would write the following patch:')
        print(patch)
        return

    # Backup
    backup = path + f'.bak.{datetime.now().strftime("%Y%m%d_%H%M%S")}'
    shutil.copy2(path, backup)
    print(f'[*] Backup saved: {backup}')

    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f'[+] Patch applied. {len(EA_HOSTS)} EA hosts redirected to {community_ip}')


def remove_patch():
    path = get_hosts_path()
    content = read_hosts(path)
    cleaned = remove_existing_patch(content)
    if cleaned == content:
        print('[*] No existing patch found.')
        return
    with open(path, 'w', encoding='utf-8') as f:
        f.write(cleaned)
    print('[+] Patch removed.')


def show_binary_patch_info():
    """
    Shows the strings that would need to be patched in the binary itself
    for a permanent redirect without hosts file manipulation.
    """
    print()
    print('=' * 70)
    print('BINARY PATCH INFO')
    print('For a permanent patch, replace these strings in the binary:')
    print('(Use a hex editor or patch tool targeting .rdata/.data sections)')
    print('=' * 70)
    patches = [
        ('winter15.gosredirector.ea.com',
         'YOUR_REDIRECTOR_HOST____________',
         'Primary redirector - game connects here first'),
        ('peach.online.ea.com',
         'YOUR_AUTH_SERVER________________',
         'Nucleus auth server'),
        ('gosca.ea.com',
         'YOUR_QOS_SERVER_________________',
         'QoS ping measurement'),
        ('demangler.ea.com',
         'YOUR_NAT_SERVER_________________',
         'NAT traversal/demangler'),
    ]
    for original, replacement, note in patches:
        print(f'  Original : {original}')
        print(f'  Replace  : {replacement}')
        print(f'  Note     : {note}')
        orig_hex = original.encode().hex()
        print(f'  Hex      : {" ".join(orig_hex[i:i+2] for i in range(0,len(orig_hex),2))}')
        print()

    print('IMPORTANT: Replace with same-length or shorter strings.')
    print('Pad shorter replacements with null bytes (0x00).')
    print('All 4 redirector variants are present and should be patched:')
    for h in EA_HOSTS:
        if 'gosredirector' in h:
            print(f'  {h}')


def main():
    parser = argparse.ArgumentParser(
        description="Mirror's Edge Catalyst community server patch")
    sub = parser.add_subparsers(dest='cmd')

    ap = sub.add_parser('apply', help='Apply hosts file patch')
    ap.add_argument('community_ip', help='IP of community server')
    ap.add_argument('--no-block-telemetry', action='store_true')
    ap.add_argument('--dry-run', action='store_true')

    sub.add_parser('remove', help='Remove hosts file patch')
    sub.add_parser('info', help='Show binary patch info')

    args = parser.parse_args()

    if args.cmd == 'apply':
        apply_patch(args.community_ip,
                    block_telemetry=not args.no_block_telemetry,
                    dry_run=args.dry_run)
    elif args.cmd == 'remove':
        remove_patch()
    elif args.cmd == 'info':
        show_binary_patch_info()
    else:
        parser.print_help()
        show_binary_patch_info()


if __name__ == '__main__':
    main()
